/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRewardsRouteImport } from './routes/_app.rewards'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSubjectSubjectIdRouteImport } from './routes/_app.subject.$subjectId'
import { Route as AppSubjectSubjectIdIndexRouteImport } from './routes/_app.subject.$subjectId.index'
import { Route as AppSubjectSubjectIdLessonIdRouteImport } from './routes/_app.subject.$subjectId.$lessonId'
import { Route as AppSubjectSubjectIdLessonIdIndexRouteImport } from './routes/_app.subject.$subjectId.$lessonId.index'
import { Route as AppSubjectSubjectIdLessonIdQuizRouteImport } from './routes/_app.subject.$subjectId.$lessonId.quiz'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectSubjectIdRoute = AppSubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectSubjectIdIndexRoute =
  AppSubjectSubjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSubjectSubjectIdRoute,
  } as any)
const AppSubjectSubjectIdLessonIdRoute =
  AppSubjectSubjectIdLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AppSubjectSubjectIdRoute,
  } as any)
const AppSubjectSubjectIdLessonIdIndexRoute =
  AppSubjectSubjectIdLessonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSubjectSubjectIdLessonIdRoute,
  } as any)
const AppSubjectSubjectIdLessonIdQuizRoute =
  AppSubjectSubjectIdLessonIdQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => AppSubjectSubjectIdLessonIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
  '/subject/$subjectId': typeof AppSubjectSubjectIdRouteWithChildren
  '/subject/$subjectId/$lessonId': typeof AppSubjectSubjectIdLessonIdRouteWithChildren
  '/subject/$subjectId/': typeof AppSubjectSubjectIdIndexRoute
  '/subject/$subjectId/$lessonId/quiz': typeof AppSubjectSubjectIdLessonIdQuizRoute
  '/subject/$subjectId/$lessonId/': typeof AppSubjectSubjectIdLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
  '/': typeof AppIndexRoute
  '/subject/$subjectId': typeof AppSubjectSubjectIdIndexRoute
  '/subject/$subjectId/$lessonId/quiz': typeof AppSubjectSubjectIdLessonIdQuizRoute
  '/subject/$subjectId/$lessonId': typeof AppSubjectSubjectIdLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/subject/$subjectId': typeof AppSubjectSubjectIdRouteWithChildren
  '/_app/subject/$subjectId/$lessonId': typeof AppSubjectSubjectIdLessonIdRouteWithChildren
  '/_app/subject/$subjectId/': typeof AppSubjectSubjectIdIndexRoute
  '/_app/subject/$subjectId/$lessonId/quiz': typeof AppSubjectSubjectIdLessonIdQuizRoute
  '/_app/subject/$subjectId/$lessonId/': typeof AppSubjectSubjectIdLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/rewards'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$lessonId'
    | '/subject/$subjectId/'
    | '/subject/$subjectId/$lessonId/quiz'
    | '/subject/$subjectId/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/rewards'
    | '/'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$lessonId/quiz'
    | '/subject/$subjectId/$lessonId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/profile'
    | '/_app/rewards'
    | '/_app/'
    | '/_app/subject/$subjectId'
    | '/_app/subject/$subjectId/$lessonId'
    | '/_app/subject/$subjectId/'
    | '/_app/subject/$subjectId/$lessonId/quiz'
    | '/_app/subject/$subjectId/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subject/$subjectId': {
      id: '/_app/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof AppSubjectSubjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subject/$subjectId/': {
      id: '/_app/subject/$subjectId/'
      path: '/'
      fullPath: '/subject/$subjectId/'
      preLoaderRoute: typeof AppSubjectSubjectIdIndexRouteImport
      parentRoute: typeof AppSubjectSubjectIdRoute
    }
    '/_app/subject/$subjectId/$lessonId': {
      id: '/_app/subject/$subjectId/$lessonId'
      path: '/$lessonId'
      fullPath: '/subject/$subjectId/$lessonId'
      preLoaderRoute: typeof AppSubjectSubjectIdLessonIdRouteImport
      parentRoute: typeof AppSubjectSubjectIdRoute
    }
    '/_app/subject/$subjectId/$lessonId/': {
      id: '/_app/subject/$subjectId/$lessonId/'
      path: '/'
      fullPath: '/subject/$subjectId/$lessonId/'
      preLoaderRoute: typeof AppSubjectSubjectIdLessonIdIndexRouteImport
      parentRoute: typeof AppSubjectSubjectIdLessonIdRoute
    }
    '/_app/subject/$subjectId/$lessonId/quiz': {
      id: '/_app/subject/$subjectId/$lessonId/quiz'
      path: '/quiz'
      fullPath: '/subject/$subjectId/$lessonId/quiz'
      preLoaderRoute: typeof AppSubjectSubjectIdLessonIdQuizRouteImport
      parentRoute: typeof AppSubjectSubjectIdLessonIdRoute
    }
  }
}

interface AppSubjectSubjectIdLessonIdRouteChildren {
  AppSubjectSubjectIdLessonIdQuizRoute: typeof AppSubjectSubjectIdLessonIdQuizRoute
  AppSubjectSubjectIdLessonIdIndexRoute: typeof AppSubjectSubjectIdLessonIdIndexRoute
}

const AppSubjectSubjectIdLessonIdRouteChildren: AppSubjectSubjectIdLessonIdRouteChildren =
  {
    AppSubjectSubjectIdLessonIdQuizRoute: AppSubjectSubjectIdLessonIdQuizRoute,
    AppSubjectSubjectIdLessonIdIndexRoute:
      AppSubjectSubjectIdLessonIdIndexRoute,
  }

const AppSubjectSubjectIdLessonIdRouteWithChildren =
  AppSubjectSubjectIdLessonIdRoute._addFileChildren(
    AppSubjectSubjectIdLessonIdRouteChildren,
  )

interface AppSubjectSubjectIdRouteChildren {
  AppSubjectSubjectIdLessonIdRoute: typeof AppSubjectSubjectIdLessonIdRouteWithChildren
  AppSubjectSubjectIdIndexRoute: typeof AppSubjectSubjectIdIndexRoute
}

const AppSubjectSubjectIdRouteChildren: AppSubjectSubjectIdRouteChildren = {
  AppSubjectSubjectIdLessonIdRoute:
    AppSubjectSubjectIdLessonIdRouteWithChildren,
  AppSubjectSubjectIdIndexRoute: AppSubjectSubjectIdIndexRoute,
}

const AppSubjectSubjectIdRouteWithChildren =
  AppSubjectSubjectIdRoute._addFileChildren(AppSubjectSubjectIdRouteChildren)

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSubjectSubjectIdRoute: typeof AppSubjectSubjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSubjectSubjectIdRoute: AppSubjectSubjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
